# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oracle_buffergets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('tnsname', models.CharField(max_length=50)),
                ('sql_time', models.BigIntegerField(blank=True)),
                ('sql_id', models.CharField(max_length=50)),
                ('buffer_gets', models.BigIntegerField(blank=True)),
                ('executions', models.BigIntegerField(blank=True)),
                ('cpu_time', models.BigIntegerField(blank=True, null=True)),
                ('elapsed_time', models.BigIntegerField(blank=True, null=True)),
                ('module', models.CharField(max_length=65, null=True)),
                ('sql_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='oracle_cputime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('tnsname', models.CharField(max_length=50)),
                ('sql_time', models.BigIntegerField(blank=True)),
                ('sql_id', models.CharField(max_length=50)),
                ('executions', models.BigIntegerField(blank=True)),
                ('elapsed_time', models.BigIntegerField(blank=True, null=True)),
                ('cpu_time', models.BigIntegerField(blank=True, null=True)),
                ('module', models.CharField(max_length=65, null=True)),
                ('sql_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='oracle_diskreads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('tnsname', models.CharField(max_length=50)),
                ('sql_time', models.BigIntegerField(blank=True)),
                ('sql_id', models.CharField(max_length=50)),
                ('disk_reads', models.BigIntegerField(blank=True)),
                ('executions', models.BigIntegerField(blank=True)),
                ('cpu_time', models.BigIntegerField(blank=True, null=True)),
                ('elapsed_time', models.BigIntegerField(blank=True, null=True)),
                ('module', models.CharField(max_length=65, null=True)),
                ('sql_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='oracle_elapsedtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('tnsname', models.CharField(max_length=50)),
                ('sql_time', models.BigIntegerField(blank=True)),
                ('sql_id', models.CharField(max_length=50)),
                ('executions', models.BigIntegerField(blank=True)),
                ('cpu_time', models.BigIntegerField(blank=True, null=True)),
                ('elapsed_time', models.BigIntegerField(blank=True, null=True)),
                ('module', models.CharField(max_length=65, null=True)),
                ('sql_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='oracle_topevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('tnsname', models.CharField(max_length=50)),
                ('sql_time', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('total_waits', models.BigIntegerField(blank=True)),
                ('total_timeouts', models.BigIntegerField(blank=True)),
                ('wait_time', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='oraclelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=50)),
                ('tnsname', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('charset', models.CharField(max_length=100)),
                ('ncharset', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('alertpath', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=300)),
                ('monitor_type', models.IntegerField(default=1)),
                ('performance_type', models.IntegerField(default=0)),
                ('hit_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='oraclestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnsname', models.CharField(max_length=100)),
                ('ipaddress', models.GenericIPAddressField()),
                ('dbsize', models.CharField(max_length=50)),
                ('tbstatus', models.CharField(max_length=200)),
                ('host_name', models.CharField(default='host', max_length=50)),
                ('version', models.CharField(default='10', max_length=50)),
                ('startup_time', models.CharField(default='2015', max_length=50)),
                ('archiver', models.CharField(default='opened', max_length=20)),
                ('sga_size', models.IntegerField(default=0)),
            ],
        ),
    ]
