# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='segmentsizechange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
                ('tnsname', models.CharField(max_length=20)),
                ('segment_time', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('segment_name', models.CharField(max_length=50)),
                ('partition_name', models.CharField(max_length=50, null=True)),
                ('segment_type', models.CharField(max_length=20)),
                ('tablespace_name', models.CharField(max_length=50)),
                ('segment_bytes', models.BigIntegerField()),
                ('blocks', models.BigIntegerField()),
            ],
        ),
    ]
