# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_segmentsizechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='linuxlist',
            fields=[
                ('ipaddress', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=50)),
                ('oracle_log', models.CharField(blank=True, max_length=300, null=True)),
                ('os_log', models.CharField(blank=True, max_length=300, null=True)),
                ('monitor_type', models.IntegerField(default=1)),
                ('performance_type', models.IntegerField(default=0)),
            ],
        ),
    ]
